### ISSUE TITLE
Unlicensed

### ISSUE THREAD

**Issue by dahlia** [spoqa/nirum.vim#8]
This project is currently unlicensed.  It should be licensed with consensus among [all contributors][1] (@admire93, @earlbread, and me).

[1]: https://github.com/spoqa/nirum.vim/graphs/contributors

**Comment by kanghyojun** [comment]
How about we use GPL? [Nirum compiler license](https://github.com/spoqa/nirum/blob/master/LICENSE) is GPL as well.

**Comment by dahlia** [comment]
FYI the compiler is licensed under GPLv3+ (where “+” means forward compatible).  I don't care any license if it's [OSI approved][1].

[1]: https://opensource.org/licenses

**Comment by dahlia** [comment]
Wonder @earlbread's opinion on this.

**Comment by earlbread** [comment]
I'm OK with any license, but it sounds good to use the same license with Nirum. :)

**Comment by kanghyojun** [comment]
Good to hear. i'll add GPLv3+.
